version: '3'
services:
  database:
    image: kosiekk/bd2-database
    container_name: bd2-postgres-container
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    image: kosiekk/bd2-backend
    container_name: bd2-backend-container
    ports:
      - "8000:8000"
    depends_on:
      - database

  frontend:
    image: kosiekk/bd2-frontend
    container_name: bd2-frontend-container
    ports:
      - "8080:80"
    depends_on:
      - database
      - backend

volumes:
  postgres_data:
    driver: local

# docker-compose -f bd2-compose.yaml up
