version: '3'
services:
  database:
    image: kosiekk/bd2-database
    container_name: bd2-postgres-container
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_HOST_AUTH_METHOD: md5
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    image: kosiekk/bd2-backend
    container_name: bd2-backend-container
    ports:
      - "8000:8000"
    depends_on:
      - database

  frontend:
    image: kosiekk/bd2-frontend
    container_name: bd2-frontend-container
    ports:
      - "80:80"
    depends_on:
      - database
      - backend

  pgadmin:
    image: dpage/pgadmin4
    container_name: bd2-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@gmail.com
      
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - database

volumes:
  postgres_data:
    driver: local

# docker-compose -f bd2-compose.yaml up
# 
# pgAdmin db connection
# Host: database
# Port: 5432
# Username: postgres
# Password: postgres